version: '2.1'
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor: node/default
    steps:
     - checkout
     - node/with-cache:
         steps:
         - run: npm install
         - run: npm test
         - run: npm lint
workflows:
  test_my_app:
    jobs:
      - test